name: tsenv
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.4
  - pandas
  - matplotlib
  - scikit-learn
  - xgboost
  - pmdarima
  - statsmodels
  - prophet
  - keras
  - tensorflow
  - pip
  - pip:
      - loguru
